# Generated by Django 4.0.3 on 2022-04-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_client_first_remove_client_last_chair_busy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='meals',
        ),
        migrations.AddField(
            model_name='client',
            name='meals',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='main.meal'),
        ),
    ]
